Validations and models specs
LarryIVC/larrys-blog pull request #3
Opened 2023-07-28 02:29 UTC by LarryIVC

## *In this pull request, I did the following:*

- [ ] Created a branch.
- [ ] Added validations for User and Post models.
- [ ] Added unit specs.
- [ ] Check the linters.

The following image shows the results of the tests run.
![image](https://github.com/LarryIVC/larrys-blog/assets/110146573/087471af-9737-418e-a7c9-6e3cc5e9521c)

2023-07-28 03:08 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @LarryIVC 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Added model specs 📌 
✔️ Tests are green 🟢 
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please write unit tests for the `Comment` and `Like` model as per requirements 🙏 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 03:08 UTC, codepantha commented on spec/models/user_spec.rb
> +  end
- [x] Well done for testing scenarios with invalid attributes. Please test a scenario where "it is valid with valid attributes" 👍 
- [x] Please write tests for the custom methods such as `return_three_recent_posts`, `update_posts_counter` in your model 🙏

2023-07-28 03:08 UTC, codepantha commented on spec/models/post_spec.rb
> +  end
- [x] Well done for testing scenarios with invalid attributes. Please test a scenario where "it is valid with valid attributes" 👍 
- [x] Please write tests for the custom methods such as `return_five_recent_comments`, `update_comments_counter`, `update_likes_counter` in your model 🙏

2023-07-28 22:37 UTC, LarryIVC commented on spec/models/user_spec.rb
> +  end
Thanks @codepantha, I will implement its changes. 👍

2023-07-28 22:37 UTC, LarryIVC commented on spec/models/post_spec.rb
> +  end
Thanks @codepantha, I will implement its changes. 👍

2023-07-28 22:55 UTC, LarryIVC commented
Here I copy the new image from the output of test.html

![image](https://github.com/LarryIVC/larrys-blog/assets/110146573/ce686df0-46db-4a42-9888-16f8a336e737)

2023-07-28 23:15 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @LarryIVC, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- Validations and model spec implemented ✔️
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 00:51 UTC, LarryIVC commented
Thanks @brainconnect93.

2023-07-29 01:05 UTC, merged